exclude: .*?/migrations/.*?
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0    # Use the ref you want to point at
  hooks:
  - id: flake8
    additional_dependencies: [flake8-tidy-imports, flake8-mutable]
    args: [--count, --show-source]
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-merge-conflict
  - id: check-yaml
- repo: https://github.com/asottile/pyupgrade
  rev: v2.23.3
  hooks:
  - id: pyupgrade
    args: [--py36-plus]
- repo: git@github.com:macisamuele/language-formatters-pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/johnfraney/flake8-markdown
  rev: v0.2.0
  hooks:
  - id: flake8-markdown
- repo: https://github.com/ambv/black
  rev: 21.7b0
  hooks:
  - id: black
    language_version: python3.6
- repo: https://github.com/PyCQA/pydocstyle
  rev: 6.1.1
  hooks:
  - id: pydocstyle
    files: ^src/
    args:
    - --ignore=D104, D100, D2, D4
    - --count
