name: django-plpy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Test Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }}, Postgres ${{matrix.postgres-version}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        postgres-version: [10, 11, 12, 13]
        django-version: [Django==2.2, Django>=3.2, <4.0]
        include:
        - python-version: 3.6
          python-long-version: 3.6.14
        - python-version: 3.7
          python-long-version: 3.7.11
        - python-version: 3.8
          python-long-version: 3.8.11
        - python-version: 3.9
          python-long-version: 3.9.6

    services:
      postgres:
        image: thorinschiffer/postgres-plpython:${{ matrix.postgres-version }}
        env:
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
        volumes:
        - ${{github.workspace}}:/app
        - /opt/hostedtoolcache/Python/${{ matrix.python-long-version }}/x64/lib/python${{ matrix.python-version }}/site-packages/:/env
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_test.txt
        pip install -U ${{matrix.django-version}}
    - name: Run Tests
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost/postgres
        PLPY_ENV_PATHS: /env,
        PLPY_PROJECT_PATH: /app
      run: |
        pip install -e .
        pytest .
