name: django-plpy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    services:
      postgres:
        image: thorinschiffer/postgres-plpython:13
        env:
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
        volumes:
        - ${{github.workspace}}:/app
        - ${LD_LIBRARY_PATH}/python${{ matrix.python-version }}/site-packages/:/env
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_test.txt
    - name: Run Tests
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost/postgres
        PLPY_ENV_PATHS: /env,
        PLPY_PROJECT_PATH: /app
      run: |
        pip install -e .
        pytest .
